[package]
name = "perceptron_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.1"
dialoguer = "0.10.2"
plotters = "0.3.4"
text_io = "0.1.12"
